### ISSUE TITLE
A question about inconsistency in the generate_maps.py related to bayesian uncertainty

### ISSUE THREAD

**Issue by kishore-greddy** [mattpoggi/mono-uncertainty#11]
Hey @mattpoggi ,

I understand that the bayesian uncertainty is calculated by adding the uncertainty from a predictive method and an empirical method, for example snap+log. However, I seem to be missing something. 

![image](https://user-images.githubusercontent.com/76811772/104359463-f8aeae80-550f-11eb-9ed0-204291be12fb.png)
In line 183, you are adding the variance from the empirical method and  adding up the uncertainties from the predicitive method(log).

![image](https://user-images.githubusercontent.com/76811772/104359631-301d5b00-5510-11eb-9422-9c0f94e99477.png)

However in line 216, you are taking the exponential for the log method, I believe this is because the uncertainties are in fact the \log of uncertainities.

Why do you not use the same torch.exp on the uncertainties while calculating it in the bayesian way, in line 183 above. What am I missing here?. 

Thanks in advance

**Comment by mattpoggi** [comment]
Hi @kishore-greddy ,
good call, the `torch.exp` should be there as well. I'll fix the uploaded code asap.
Anyway, I've double checked the results and the numbers obtained without `torch.exp` are almost identical to the correct implementation (the predictive uncertainty seems dominant w.r.t. empirical one).
Thanks for pointing it out :+1:

**Comment by kishore-greddy** [comment]
No problem :) , Thank you for fixing it.
