### ISSUE TITLE
Problem with Bayesian uncertainty method

### ISSUE THREAD

**Issue by brandonwagstaff** [mattpoggi/mono-uncertainty#18]
Hi There,

I'm wondering if there is a discrepancy between this line of code and equation 17 in the paper that computes the full uncertainty for the Bayesian approach:

https://github.com/mattpoggi/mono-uncertainty/blob/07a8d647a159cf049bb72c2e7ed70fc6c794ea38/generate_maps.py#L183

As far as I'm aware, the empirical variance from the ensemble should be added with the square of the learned uncertainty output. Am I correct in associating this line of code with equation 17 of the paper? If so, there might be an issue here. I was wondering if this affects the visualization of uncertainties in the paper.

Thanks!

**Comment by mattpoggi** [comment]
Hi @brandonwagstaff,
yep, that's related to #11 , a missing torch.exp (and squared term as well) was missing in the first code release.
I'm fixing this, thanks for pointing it out. 

As you correctly point out, this affects the colormap scaling of the qualitative results, while numerically does not make a real difference (usually, the second decimal in RMSE metrics).

**Comment by brandonwagstaff** [comment]
Got it, thanks for the response!
