### ISSUE TITLE
some questions about my implementation

### ISSUE THREAD

**Issue by Bowwowlol** [mattpoggi/mono-uncertainty#23]
Hi, @mattpoggi, 
Thanks for your excellent work!!
I have some questions about my implementation.
1.  In the depth decoder (S), it is output 4 scale disparity and uncertainty, I would like to know that have you calculated all scale outputs when you implemented eq.14?
![image](https://user-images.githubusercontent.com/32257352/170857865-63d78251-5593-4a7a-8fea-cb4eadc7605a.png)

2.  If my uncertainty has some negative values, Should I limit it to>0?

**Comment by mattpoggi** [comment]
Hi @Bowwowlol,
1. depth and uncertainty at each scale are upsampled to full resolution when computing the loss
2. if you assume your output uncertainty is u=log(uncertainty), you should be fine (then replace sigma with exp(u) in the loss function)

**Comment by Bowwowlol** [comment]
Hi, @mattpoggi, 
Thank you for the quick reply!!
I really appreciate your help in resolving problems, That is very helpful to me.
Good luck!!
