### ISSUE TITLE
S and MS models uploaded

### ISSUE THREAD

**Issue by MedlarTea** [mattpoggi/mono-uncertainty#5]
Thanks for your excellent works!!!

**Comment by MedlarTea** [comment]
I'm curious about S and MS models uploading time, which are useful for me.
Thanks again for your code sharing!!!

**Comment by mattpoggi** [comment]
Hi @MedlarTea ,
sorry, I have been trapped in deadlines and I just forgot about it. You can now find the links to S and MS models as well.

**Comment by MedlarTea** [comment]
Oh,thanks!!
best wishes!
