### ISSUE TITLE
which split should I choose when training?

### ISSUE THREAD

**Issue by freshjh** [mattpoggi/mono-uncertainty#6]
Hi, thanks for your greate work! And I am confused about the **dataset split** in training, can you tell me which split files were choosed when you training the model?  is 'eigen zhou' ? or 'benchmark'? or others. it is my first time to use kitti_dataset. Thanks!

**Comment by mattpoggi** [comment]
Hi @freshjh ,
as for monodepth2, we used `eigen_zhou` to train on sequences (M, MS) and `eigen_full` when using stereo pairs alone (S).

**Comment by freshjh** [comment]
thank you very much！
